name: post_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.7
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true